# .streamlit/secrets.toml
OPENBB_PAT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3Rva2VuIjoiQ0JtdktHeFJFdlhUcnVyOGR2UmJUbkZKM2RTZVV1WG91eXRaeTRSTCIsImV4cCI6MTgwMzU3MDAzNH0.kPdymjPQboUBOXWOiD7We3M6GF1rqZqjgwEfYrcfOcI"
FMP_API_KEY = "8Bb25O4BmNkIJhDiwTC3zZ9ayPReoOhW"
ANTHROPIC_API_KEY = "dein_claude_key"